server:
  port: 9096

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id : microservice-one
          uri: lb://microservice-one
          predicates:
          - Path=/message/**
        - id: microservice-one
          uri: lb://microservice-one
          predicates:
          - Path=/message/**



